from pathlib import Path
path = Path(r"src/screens/eic/NetworkDashboard.js")
text = path.read_text()
old = "      cardHeader: {\r\n        paddingTop: theme.spacing(0.5),\r\n        paddingBottom: theme.spacing(0.3),\r\n        borderBottomWidth: 1,\r\n        borderBottomColor: theme.colors.borderSubtle,\r\n        marginBottom: theme.spacing(0.3),\r\n      },\r\n      msTitle: {\r\n        fontSize: theme.typography.sizes.title,\r\n        fontWeight: theme.typTypography?.weightBold || \"700\",\r\n        color: theme.colors.textPrimary,\r\n        marginBottom: theme.spacing(0.05),\r\n      },\r\n      msId: {\r\n        fontSize: theme.typTypography?.sizes.caption || 12,\r\n        color: theme.colors.textSecondary,\r\n        marginTop: theme.spacing(0.05),\r\n      },\r\n      msMeta: {\r\n        fontSize: theme.typTypography?.sizes.body || 14,\r\n        color: theme.colors.textSecondary,\r\n        marginTop: theme.spacing(0.05),\r\n      },\r\n"
new = "      cardHeader: {\r\n        paddingTop: theme.spacing(0.15),\r\n        paddingBottom: theme.spacing(0.15),\r\n        borderBottomWidth: 1,\r\n        borderBottomColor: theme.colors.borderSubtle,\r\n        marginBottom: theme.spacing(0.15),\r\n        gap: theme.spacing(0.15),\r\n      },\r\n      fieldRow: {\r\n        flexDirection: \"row\",\r\n        alignItems: \"baseline\",\r\n        gap: theme.spacing(0.75),\r\n      },\r\n      fieldLabel: {\r\n        fontSize: theme.typTypography?.sizes.caption || 12,\r\n        color: theme.colors.textSecondary,\r\n        textTransform: \"uppercase\",\r\n        letterSpacing: 0.5,\r\n      },\r\n      fieldValue: {\r\n        fontSize: theme.typTypography?.sizes.body || 14,\r\n        color: theme.colors.textPrimary,\r\n        fontWeight: theme.typTypography?.weightSemiBold || \"600\",\r\n        flexShrink: 1,\r\n      },\r\n"
if old not in text:
    raise SystemExit('header block not found')
text = text.replace(old, new)
path.write_text(text)
